context:
  name: toppra
  version: "0.6.4"

recipe:
  name: toppra
  version: ${{ version }}

source:
  # url: https://github.com/hungpham2511/toppra/archive/refs/tags/v${{ version }}.tar.gz
  # sha256: 31213336fc36a69e8003808e7317773ba7c78e503c8cbd6d01fe2d50660e3294
  # TODO: Change this with upstream
  url: https://github.com/open-planning/toppra.git
  rev: 676a21117a6f2d9196776fd058179737858c7be9

build:
  number: 1

outputs:
  - package:
      name: libtoppra
      version: ${{ version }}
    build:
      script:
        - if: unix
          then: build.sh
        - if: win
          then: build.bat
    requirements:
      run_exports:
        - ${{ pin_subpackage("libtoppra", upper_bound="x.x.x") }}
      build:
        - ${{ stdlib('c') }}
        - ${{ compiler('cxx') }}
        - cmake
        - ninja
      host:
        - eigen
        - gtest
      run:
        - eigen
      ignore_run_exports:
        by_name:
          - gtest
        from_package:
          - gtest
    tests:
      - package_contents:
          lib:
            - toppra

about:
  homepage: https://github.com/hungpham2511/toppra
  license: MIT
  license_file: LICENSE
  summary: Path parameterization for robots
  repository: https://github.com/hungpham2511/toppra
  documentation: https://hungpham2511.github.io/toppra/index.html

extra:
  feedstock-name: toppra
  recipe-maintainers:
    - sea-bass
