context:
  name: toppra
  version: "0.6.6-1"

recipe:
  name: toppra
  version: ${{ version }}

source:
  url: https://github.com/hungpham2511/toppra/archive/refs/tags/${{ version }}.tar.gz
  sha256: 11f7049eb94e5683b89c586912b3a872eda3bf7be476f709d1e3f8d8241ac525

build:
  number: 0

outputs:
  - package:
      name: libtoppra
      version: ${{ version }}
    build:
      script:
        - if: unix
          then: build.sh
        - if: win
          then: build.bat
    requirements:
      run_exports:
        - ${{ pin_subpackage("libtoppra", upper_bound="x.x.x") }}
      build:
        - ${{ stdlib('c') }}
        - ${{ compiler('cxx') }}
        - cmake
        - ninja
      host:
        - eigen
        - gtest
      run:
        - eigen
      ignore_run_exports:
        by_name:
          - gtest
        from_package:
          - gtest
    tests:
      - if: unix
        then:
          package_contents:
            lib:
              - toppra
      - if: win
        then:
          package_contents:
            files:
              - Library/lib/toppra.dll

about:
  homepage: https://github.com/hungpham2511/toppra
  license: MIT
  license_file: LICENSE
  summary: Path parameterization for robots
  repository: https://github.com/hungpham2511/toppra
  documentation: https://hungpham2511.github.io/toppra/index.html

extra:
  feedstock-name: toppra
  recipe-maintainers:
    - sea-bass
